### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by NAIM6246** [NAIM6246/Basic-Golang-Learning#5]
https://github.com/NAIM6246/Basic-Golang-Learning/blob/de207eddc338ab54bfb76992f82e01baa4f623d3/handler/ArticleHandler.go#L33

**Comment by rafiulgits** [comment]
https://github.com/NAIM6246/Basic-Golang-Learning/blob/de207eddc338ab54bfb76992f82e01baa4f623d3/handler/ArticleHandler.go#L41

why panic at this line? you already write a response. Remove this and make the status code `400`

**Comment by rafiulgits** [comment]
https://github.com/NAIM6246/Basic-Golang-Learning/blob/de207eddc338ab54bfb76992f82e01baa4f623d3/handler/ArticleHandler.go#L45

as you handle the service error then just response with `HTTP 400` a bed request

**Comment by rafiulgits** [comment]
I think by resolving these 2 panic with proper HTTP response, everything will work fine

**Comment by NAIM6246** [comment]
after removing those 2 panic's everything works fine.
no more error in post method.

**Comment by rafiulgits** [comment]
👍  then close this issue
